apiVersion: v1
name: monitoring
description: A helm chart for monitoring
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: 62.7.0
    repository: https://prometheus-community.github.io/helm-charts
    alias: kube-prometheus-stack
