name: bird-images
namespace: bird
replicas: 4
image:
  repository: adityaganesh27/kubeadm-demo-bird-image
  tag: e3f711bx
  pullPolicy: IfNotPresent
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
configs:
  port: "8001"
  LOG_LEVEL: debug
  UNSPLASH_API: https://api.unsplash.com
  DEFAULT_BIRD_IMAGE: "https://www.pokemonmillennium.net/wp-content/uploads/2015/11/missingno.png"
secrets:
  secretStore: sdk-prod-secret-store
  secretPath: prod
  data:
    - name: UNSPLASH_API_KEY
      property: UNSPLASH_API_KEY
resources:
  limits:
    cpu: 256m
    memory: 256Mi
  requests:
    cpu: 128m
    memory: 128Mi
autoscaling:
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Min
podAnnotations: {}
service:
  type: ClusterIP
  port: 8000
probes:
  healthEndpoint: /health
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
affinity:
  key: type
  value: ondemand
  podAntiAffinity:
    topologyKey: kubernetes.io/hostname
    weight: 100

